<?php

namespace AppBundle\Repository;

/**
 * animateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class animateurRepository extends \Doctrine\ORM\EntityRepository
{
}
