<?php

namespace AppBundle\Repository;

/**
 * garderieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class garderieRepository extends \Doctrine\ORM\EntityRepository
{
}
