<?php

namespace AppBundle\Repository;

/**
 * info_santeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class info_santeRepository extends \Doctrine\ORM\EntityRepository
{
}
