<?php

namespace AppBundle\Repository;

/**
 * suivieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class suivieRepository extends \Doctrine\ORM\EntityRepository
{
}
