enfant:
    resource: "@EnfantBundle/Resources/config/routing.yml"
    prefix:   /enfant

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"